export const LIST_TRANFORMS = {
  invoicePartnerId: 'validator.keyword.invoicePartnerId',
  orderId: 'validator.keyword.orderId',
  description: 'validator.keyword.description',
  amount: 'validator.keyword.amount',
  methodId: 'validator.keyword.methodId',
  customerId: 'validator.keyword.customerId',
  name: 'validator.keyword.name',
  deal: 'validator.keyword.deal',
  email: 'validator.keyword.email',
  password: 'validator.keyword.password',
  confirm_password: 'validator.keyword.confirm_password',
  first_name: 'validator.keyword.first_name',
  firstName: 'validator.keyword.first_name',
  last_name: 'validator.keyword.last_name',
  gender: 'validator.keyword.gender',
  phone: 'validator.keyword.phone',
  fax: 'validator.keyword.fax',
  currencyId: 'validator.keyword.currency',
  customer_name: 'validator.keyword.customer_name',
  deal_name: 'validator.keyword.deal_name',
  dealId: 'validator.keyword.dealId',
  role: 'validator.keyword.role',
  task:'validator.keyword.task',
  level_customer:"validator.keyword.level_customer",
  sale_partner:'validator.keyword.sale_partner',
  order_id:'validator.keyword.order_id',
  industry_name:'validator.keyword.industry_name',
  invoice_category_id:'validator.keyword.invoice_category_id'
};

