// Auth
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOADING = "LOADING";
export const LOADING_COMMENT = "LOADING_COMMENT";
export const LOADING_SEND_MAIL = "LOADING_SEND_MAIL";
export const SIGN_OUT = "SIGN_OUT";
export const ERROR = "ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const NEW_PASSWORD = "NEW_PASSWORD";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CLEAR_DATA = "CLEAR_DATA";
export const FORGOT_PASSWOPD = "FORGOT_PASSWORD"
export const CHECK_RESET_TOKEN = "CHECK_RESET_TOKEN"
export const CHANGE_PASSWORD_TOKEN = "CHANGE_PASSWORD_TOKEN"

// action - customization reducer
export const SET_MENU = "@customization/SET_MENU";
export const MENU_TOGGLE = "@customization/MENU_TOGGLE";
export const MENU_OPEN = "@customization/MENU_OPEN";
export const SET_FONT_FAMILY = "@customization/SET_FONT_FAMILY";
export const SET_BORDER_RADIUS = "@customization/SET_BORDER_RADIUS";

export const SEARCH_USER = "SEARCH_USER";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";

//Contact
export const SEARCH_CONTACT = "SEARCH_CONTACT";
export const GET_CONTACT_DETAIL = "GET_CONTACT_DETAIL";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DETAIL_CONTACT = "DETAIL_CONTACT";
export const GET_CONTACT_LIST_BY_CUSTOMER_ID =
  "GET_CONTACT_LIST_BY_CUSTOMER_ID";

//Deal
export const SEARCH_DEAL = "SEARCH_DEAL";
export const GET_DEAL_DETAIL = "GET_DEAL_DETAIL";
export const DELETE_DEAL = "DELETE_DEAL";
export const CREATE_DEAL = "CREATE_DEAL";
export const UPDATE_DEAL = "UPDATE_DEAL";
export const DETAIL_DEAL = "DETAIL_DEAL";
export const UPDATE_STATUS_DEAL = "UPDATE_STATUS_DEAL";

//User
export const DELETE_USER = "DELETE_USER";

//Customer

export const SEARCH_CUSTOMER = "SEARCH_CUSTOMER";
export const SEARCH_NAME_ID_CUSTOMER = "SEARCH_NAME_ID_CUSTOMER";
export const DETAIL_CUSTOMER = "DETAIL_CUSTOMER";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const MERGE_CUSTOMER = "MEGER_CUSTOMER";
export const DETAIL_CID = "DETAIL_CID";
export const LIST_CONTACT = "LIST_CONTACT";
export const LIST_DEAL = "LIST_DEAL";
export const LIST_ORDER = "LIST_ORDER";
export const LIST_ORDER_HAS_INVOICE = "LIST_ORDER_HAS_INVOICE";
export const LIST_INVOICE_BY_CUSTOMER_ID = "LIST_INVOICE_BY_CUSTOMER_ID";

//Tag

export const SEARCH_TAG = "SEARCH_TAG";
export const CREATE_TAG = "CREATE_TAG";

//Industry
export const GET_INDUSTRY = "GET_INDUSTRY";
export const CREATE_INDUSTRY = "CREATE_INDUSTRY";
export const DELETE_INDUSTRY = "DELETE_INDUSTRY";
export const UPDATE_INDUSTRY = "UPDATE_INDUSTRY";

//Countries
export const GET_COUNTRIES = "GET_COUNTRIES";
export const CREATE_COUNTRIES = "CREATE_COUNTRIES";
export const DELETE_COUNTRIES = "DELETE_COUNTRIES";

//Cities
export const GET_CITIES = "GET_CITIES";
export const CREATE_CITITES = "CREATE_CITIES";

//Employee
export const GET_EMPLOYEE = "GET_EMPLOYEE";

// Category
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";

// Status
export const GET_STATUS_LIST = "GET_STATUS_LIST";

// Order
export const SEARCH_ORDER = "SEARCH_ORDER";
export const DETAIL_ORDER = "DETAIL_ORDER";
export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const GET_ORDER_LIST_BY_DEAL_ID = "GET_ORDER_LIST_BY_DEAL_ID";
export const GET_VALID_INVOICE_LIST_BY_ORDER_ID =
  "GET_VALID_INVOICE_LIST_BY_ORDER_ID";

//billingType
export const GET_BILLING_LIST = "GET_BILLING_LIST";

// Order item
export const GET_ORDER_ITEM_LIST_BY_ORDER_ID =
  "GET_ORDER_ITEM_LIST_BY_ORDER_ID";
export const CREATE_ORDER_ITEM = "CREATE_ORDER_ITEM";
export const DELETE_ORDER_ITEM = "DELETE_ORDER_ITEM";
export const DETAIL_ORDER_ITEM = "DETAIL_ORDER_ITEM";
export const UPDATE_ORDER_ITEM = "UPDATE_ORDER_ITEM";

// Order status
export const GET_ORDER_STATUS_LIST = "GET_ORDER_STATUS_LIST";
//Curency
export const GET_CURRENCY_LIST = "GET_CURRENCY_LIST";

// Invoice
export const GET_INVOICE_STATUS = "GET_INVOICE_STATUS";
export const CREATE_INVOICE = "CREATE_INVOICE";
export const DETAIL_INVOICE = "DETAIL_INVOICE";
export const GET_INVOICE_BY_ORDER_ID = "GET_INVOICE_BY_ORDER_ID";
export const GET_INVOICE_BY_CUSTOMER_ID = "GET_INVOICE_BY_CUSTOMER_ID";
export const SEARCH_INVOICE = "SEARCH_INVOICE";
export const UPDATE_STATUS_INVOICE = "UPDATE_STATUS_INVOICE";
export const UPDATE_DETAIL_INVOICE = "UPDATE_DETAIL_INVOICE";
export const UPDATE_INVOICE_CODE = "UPDATE_INVOICE_CODE";
export const GET_INVOICE_BY_CODE = "GET_INVOICE_BY_CODE";
export const REFRESH_INVOICE_STATUS = "REFRESH_INVOICE_STATUS";
export const DELETE_INVOICE = "DELETE_INVOICE";

// Invoice category
export const GET_INVOICE_CATEGORY_LIST = "GET_INVOICE_CATEGORY_LIST";

// Payment
export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const SEARCH_PAYMENT = "SEARCH_PAYMENT";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const GET_PAYMENT_BY_ORDER_ID = "GET_PAYMENT_BY_ORDER_ID";
export const GET_PAYMENT = "GET_PAYMENT";

// Get payment method
export const GET_PAYMENT_METHODS = "GET_PAYMENT_METHODS";
//Payments
export const GET_PAYMENTS_LIST_BY_CUSTOMER_ID =
  "GET_PAYMENTS_LIST_BY_CUSTOMER_ID";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
// Task
export const GET_LIST_TASK = "GET_LIST_TASK";
export const GET_TOTAL_LIST_TASK = "GET_TOTAL_LIST_TASK";
export const CREATE_TASK = "CREATE_TASK";
export const GET_TASK = "GET_TASK";
export const ARCHIVE_TASK = "ARCHIVE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const GET_TASK_OBJECT = "GET_TASK_OBJECT";
export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS";

// Checklist
export const CREATE_CHECKLIST = "CREATE_CHECKLIST";
export const DELETE_CHECKLIST = "DELETE_CHECKLIST";

// Checklist Item
export const CREATE_CHECKLIST_ITEM = "CREATE_CHECKLIST_ITEM";
export const DELETE_CHECKLIST_ITEM = "DELETE_CHECKLIST_ITEM";
export const UPDATE_CHECKLIST_ITEM = "UPDATE_CHECKLIST_ITEM";

//Profile
export const GET_DETAIL_PROFILE = "GET_DETAIL_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PASSWORD_PROFILE = "UPDATE_PASSWORD_PROFILE";
export const UPDATE_USER_LANGUAGES = "UPDATE_USER_LANGUAGES";

//Card Image
export const GET_CARD_IMAGE = "GET_CARD_IMAGE";
export const GET_AVATAR_CONTACT = "GET_AVATAR_CONTACT";

//Comment
export const CREATE_COMMENT = "CREATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPDATE_COMMENT = "UPDATE_COMMENT";

//Customer-Level
export const GET_CUSTOMER_LEVEL = "GET_CUSTOMER_LEVEL";
export const CREATE_CUSTOMER_LEVEL = "CREATE_CUSTOMER_LEVEL";
export const DELETE_CUSTOMER_LEVEL = "DELETE_CUSTOMER_LEVEL";
export const UPDATE_CUSTOMER_LEVEL = "UPDATE_CUSTOMER_LEVEL";

//Notifications
export const GET_LIST_NOTIFIATION = "GET_LIST_NOTIFIATION";
export const UPDATE_SEEN_ALL_NOTIFICATION = "UPDATE_SEEN_ALL_NOTIFICATION";

//Lognote

export const GET_LIST_LOGNOTE = "GET_LIST_LOGNOTE";

//Sale-Channel
export const GET_SALE_CHANNEL = "GET_SALE_CHANNEL";
export const CREATE_SALE_CHANNEL = "CREATE_SALE_CHANNEL";
export const DELETE_SALE_CHANNEL = "DELETE_SALE_CHANNEL";

//System

export const GET_SYSTEM_INFOR = "GET_SYSTEM_INFOR";
export const CREATE_SYSTEM = "CREATE_SYSTEM";

//partner

export const CREATE_PARTNER = "CREATE_PARTNER";
export const LIST_PARTNER = "LIST_PARTNER";
export const DELETE_PARTNER = "DELETE_PARTNER";
export const DETAIL_PARTNER = "DETAIL_PARTNER";
export const UPDATE_PARTNER = "UPDATE_PARTNER";
export const PARTNER_CONTRACT = "PARTNER_CONTRACT"

//partner invoice
export const LIST_PARTNER_INVOICE = "LIST_PARTNER_INVOICE";
export const GET_INVOICE_PARTNER_BY_ORDER = "GET_INVOICE_PARTNER_BY_ORDER";
export const DETAIL_PARTNER_INVOICE = "DETAIL_PARTNER_INVOICE";
export const UPDATE_INVOICE_PARTNER_CODE = "UPDATE_INVOICE_PARTNER_CODE";
export const UPDATE_DETAIL_INVOICE_PARTNER = "UPDATE_DETAIL_INVOICE_PARTNER";

//partner payment
export const LIST_PAYMENT_PARTNER = "LIST_PAYMENT_PARTNER";
export const GET_ORDER_BY_PARTNER = "GET_ORDER_BY_PARTNER";
export const CREATE_PARTNER_PAYMENT = "CREATE_PARTNER_PAYMENT";
export const DETAIL_PAYMENT_PARTNER = "DETAIL_PAYMENT_PARTNER";
export const UPDATE_PARTNER_PAYMENT = "UPDATE_PARTNER_PAYMENT";
export const DELETE_PARTNER_PAYMENT = "DELETE_PARTNER_PAYMENT";
export const CREATE_PAYMENT_MANY_INVOICE = "CREATE_PAYMENT_MANY_INVOICE";
